### ISSUE TITLE
A more complex config example

### ISSUE THREAD

**Issue by ruslantalpa** [pintsized/ledge#111]
Is there a more complex example for a configuration?
For example i am trying to cache an REST-like API where each GET request is cacheable based on endpoint+session+querystring and each POST/UPDATE/DELETE should purge all cached items for that endpoint.
Do you have a config similar to that that you can post in a gist?
Thank you

**Comment by ruslantalpa** [comment]
Got it to work and cache requests, haven't figured yet how to purge keys based on a specific pattern.
tried sending PURGE requests to this location
```
location /purge/ {
   rewrite ^(.*)$ "*hardcodedpattern*" break;
   content_by_lua 'ledge:run()';
}
```

in the hopes that both of these keys would be deleted
```
ledge:cache:http:localhost:/hardcodedpattern
ledge:cache:http:localhost:/hardcodedpattern:param=value
```
but it looks like only the first key is being deleted
Could you provide a "location" config that would take the pattern as a parameter
```
/purge/patterngoeshere
/purge/?pattern=patterngoeshere
```
and invalidates all the keys that contain the ```patterngoeshere``` string?

once i have a location like this i can mark it "interal" then use subrequests to that location in order to delete some keys when for example the request is a POST
Thank you

**Comment by ruslantalpa** [comment]
Got purge to work like this
```
location /purge/ {
   content_by_lua '
       ledge:config_set("cache_key_spec", { "* patterngoeshere*" })
       ledge:run()
   ';
}
```
Is this the (basic) correct way of doing it?

**Comment by hamishforbes** [comment]
Hey,

That'll work but its a bit of a hack, cache keys and wildcard purging is intended to work more like

```
location / {
    content_by_lua '
        local session = get_session_id_somehow()
        ledge:config_set("cache_key_spec", {
            session,
            ngx.var.scheme,
            ngx.var.host,
            ngx.var.uri,
            ngx.var.args,
        })
        ledge:run()
    ';
}
```

Then a GET request for /foo/bar will be cached using a key including your session ID.

A request using the PURGE method for /foo/* with that same session ID would then purge all matching cache entries.

If you need a PURGE to clear all keys for all sessions then you would have to force a * into the cache key spec similar to how you've done it already.


To be honest with you it sounds like your use case might not be the best fit for Ledge.
The primary use case for Ledge is as caching reverse proxy for websites, as you've found you can definitely force Ledge into doing what you need.
However you might be better off writing a simple bit of Lua to write responses into Redis or a shared dictionary.
This would make it easier to use the specific logic you require for invalidation and keys?

Do you need to make use of the cache control features within HTTP, like respecting Cache-Control request and response headers?
Or use ESI and the other advanced features Ledge offers?

Hamish

**Comment by ruslantalpa** [comment]
Thank you for the reply,
Actually my upstream is not returning any Cache-Control header, i am setting them manually.
I am trying to put a transparent cache on top of a specific upstream for which i know the behaviour and i know how to calculate the key for each get request and i know what keys are invalidated by a POST/DELETE request

For example
```
GET /endpoint1 # key = endpoint1
GET /endpoint2?include=endpoint1 # key = endpoint1:endpoint2
POST /endpoint1 # invalidates both of the above keys
```

I also tried invalidating multiple patterns at the same time with
```
ledge:config_set("cache_key_spec", { "*endpoint1*" })
ledge:run()
ledge:config_set("cache_key_spec", { "*endpoint1*" })
ledge:run()
```

but that worked only for the first step.
How could i decompose the "run" function so that i can use "_M.expire" (not sure if i really need this though ...)

So your suggestion is write a simplified version of ledge that stores the response of the upstream in redis? Do you know a short example somewhere on how to do that (intercept GET, check if key exists and serve, if not let the proxy_pass do the work)?
Thank you
