### ISSUE TITLE
How to avoid caching errors? (404, 403..)

### ISSUE THREAD

**Issue by keen99** [pintsized/ledge#117]
Is it possible to define http status codes to either cache or not cache?  We're seeing 404s and 403s being cached - while I understand some folks might want to cache those, we don't.

If it's not configurable - a pointer to where to hack this in would be great... I got a bit lost last time I looked, but it's pretty high priority for me today since it means we cache error state from intermittent errors from our upstream. :/

**Comment by hamishforbes** [comment]
Hi, There's nothing inherently uncacheable about 'error' responses and Ledge won't cache responses without headers allowing caching, are your upstreams sending cache headers even though you don't want them to?

You can definitely use the `origin_fetched` event to solve this though. It's not really a hack either, Ledge is intended to follow the HTTP spec as best we can but provide scriptable hooks to allow custom behaviour exactly like this.

Try something like (untested code)...

```lua
ledge:bind("origin_fetched", function(res) 
     if res.status >= 400 and res.status <= 403 then
         res.header["Cache-Control"] = "private, no-cache, no-store"
    end
end)
```

**Comment by keen99** [comment]
oh good call there - thanks. 

our upstream treats their data as uncachable, so we're forcing the cache-control header in lua before ledge - so...duh. :)  perfect place to hook in!

thanks!

still seems like this would be nice to have as a feature - store only responses that match XXX type of thing.

thanks!

**Comment by hamishforbes** [comment]
Perhaps, I don't know if we want to clutter the codebase with lots of config options for things that can be scripted in almost as many lines of Lua as it takes to set the option though.

I'll leave that one up to @pintsized to decide tho 👍

**Comment by keen99** [comment]
advantage of documented config options - new (and old..) users have a direct path to doing these things in a well known tested fashion, instead of "lets go figure it out with code" :)

(this is my exact argument for wanting to use someone else's caching implementation - we could write our own code to do it, but using something other people are already using and already has the kinks work out of...)

**Comment by hamishforbes** [comment]
That is true, but I don't think that's really the goal for Ledge. 
The intention, I'd say, is to provide something scriptable and therefore very flexible for more complex / advanced caching problems.

If you just need a simple system to cache 200 responses then the nginx proxy_cache module is actually perfect! :)

**Comment by keen99** [comment]
> f you just need a simple system to cache 200 responses then the nginx proxy_cache module is actually perfect! :)

unless you need things like password auth to redis.... then you're back into DIY land.   :)

**Comment by pintsized** [comment]
I'm with Hamish on keeping this kind of thing to the scripting hooks (or indeed anywhere between your origin and Ledge). I take your point about documented options being clearer for others, but we should really stick to the spec where possible, for sanity. Things can get complicated pretty quickly otherwise. That is, what fits your case perfectly doesn't quite fit someone else's etc.

It's best to let Ledge do the "correct" thing with whatever you give it, and control behaviours using HTTP semantics such as the Cache-Control header. Where possible, configuration options should be limited to system configuration / tuning in my view.

**Comment by keen99** [comment]
Thanks.  For future readers, here's what I did for my specific needs - obviously I wouldn't normally suggest a 1 year cache time... so dont use this as it sits! :)

```

-- Add some cache headers.  Ledge will assume they came from the origin and override origin header
ledge:bind("origin_fetched", function(res)
    -- https://github.com/pintsized/ledge/issues/117#issuecomment-223327520
    -- the rules:
    -- non-200s - ie 404s, cache for 5 minutes
    -- 403s, do not cache at all
    -- for either of these, serve stale if we can. (stale_if_error age)
    -- 50x is already not cached.
    if res.status == 200 then
      res.header["Cache-Control"] = "max-age=" .. 31536000
    elseif res.status == 403 then
      res.header["Cache-Control"] = "private, no-cache, no-store"
    else
      -- note that other than Age and X-Cache: MISS, there's no log of this event at all, nor the error that triggers it..
      -- anything not 200 or 403
      res.header["Cache-Control"] = "max-age=300"
    end
end)
-- if error, this returns a MISS -and- Age and stale content.
-- 1 year
ledge:config_set("stale_if_error", 31536000)

```
