### ISSUE TITLE
feature request:  optionally compress body stored in redis

### ISSUE THREAD

**Issue by keen99** [pintsized/ledge#118]
use case:  we cache a lot of large easily compressible (json) data with long TTLs (1 year), from an external provider with extremely low request and rate limits.   The upstream doesn't compress if we send an accept-encoding header, so we don't have that option.

it would be great if we could compress this on the fly during cache write.   obviously ledge already has uncompress logic for serving compressed bodies to clients who dont accept this - so seems like it would be ~easy.

obviously there are performance impacts - but I'd think they'd be very similar to the uncompress.   For our case, with 1 request per second upstream limits, it would be invisible. :)

thanks!

**Comment by hamishforbes** [comment]
Yeah I agree this would be a nice feature. 👍 

It makes the various different codepaths a little hairy when you throw ESI into the mix which I think is the only reason it's not been done.

You could hack this in the meantime by proxying through nginx before going to your upstream though.
e.g. you create a proxy_pass config on an alternate port that has gzip enabled and proxies to your real upstream.
Then set Ledge's upstream to be 127.0.0.1 and your alternate port

**Comment by keen99** [comment]
So I've got this "working" - ledge calls an upstream server on localhost:xyz that supports gzipping the proxy content.  I can hit the port and get valid gziped content in return - it DOES require specifying the Accept-Encoding header in the request, though.

So two issues:

How to get ledge to set the Accept-Encoding header?  I haven't found a "always compress regardless of the client request option for nginx's gzip on; yet...)

For the above, my current testing workaround is to make my cache-miss request include the header, which results in a valid gzipped reponse to the client, and stores not-text in redis.


The real problem comes in with the cache-hit calls.   By all appearances, ledge isn't storing the content gzipped.  If I just add Accept-Encoding: gzip to my curl request and drop the body into a file (this is the cache hit):

    %% file test.out
    test.out: data

debug log shows: 

    2016/06/06 18:39:41 [debug] 35#0: *7 [lua] ledge.lua:2037: e(): #t: considering_gzip_inflate
    2016/06/06 18:39:41 [debug] 35#0: *7 [lua] ledge.lua:2047: e(): #e: gzip_inflate_disabled


vs storing a compressed body from google:

    curl -H"Accept-Encoding: gzip" -v www.google.com/ > google.out
    %% file google.out
    google.out: gzip compressed data, max compression


The same request to ledge without the gzip header set results in an empty body response - ledge does try to uncompress it:

```
2016/06/06 18:52:00 [debug] 35#0: *15 [lua] ledge.lua:2037: e(): #t: considering_gzip_inflate
2016/06/06 18:52:00 [debug] 35#0: *15 [lua] ledge.lua:2047: e(): #e: gzip_inflate_enabled
2016/06/06 18:52:00 [debug] 35#0: *15 [lua] ledge.lua:2074: e(): #a: install_gzip_decoder
2016/06/06 18:52:00 [debug] 35#0: *15 [lua] ledge.lua:632: filter_body_reader(): gzip_decoder(cache_body_reader)
2016/06/06 18:52:00 [debug] 35#0: *15 [lua] ledge.lua:2037: e(): #t: preparing_response
```

    %% wc -c test.out
           0 test.out



Here's what redis has:

127.0.0.1:6379> keys *body
1) "ledge:cache:127.0.0.1:/myrequest:body"
127.0.0.1:6379> lpop "ledge:cache:127.0.0.1:/myrequest::3e925e37:body"
"\xa4\x98\xddn\xdbF\x10\x85_\x85\xe8U\x0bd\x0b\xee\x92\xbb$ug\xc7vR#\xaa\x8c(\xf0\xfd\x8a\\&D$\xd1\xa0m\xa0\xcd\xd3\xf7\xcc\xd2\xe2\xfeP\xb2e\x14\xf0\x8d\xad\xd1X\xd47g\xe6\xccP\x03\xa0\x8f\x12`\xa7\xb8d\xca\xe3A\xcf3\x99*\xc2\xec\xa0\x87\xfa\x17oA\xa7v\xe0\xa0\xaf\x9f\xfeL\xee\x0c\xda\xf0\xe3\xe6y\xa0i36\x86\xb8\x04\xd6f\xd7\xed\xfb-\x9a\xc0\r\x15MT\x03\x99\x15\xe4\xac\x06\\\xe8\xab\xe2\x7f\xde\x9b\xa6\xa3\xb6\x18\xd6@\x8a\xca\xca\x99\xa0\xac\xa7j@\xcaE.\xfd\x1a\b\xd4\xcf\x8b:\xad\x05\xd2du\x86\xc1$e\x06\xf5\x17-\xd3U\xb5\xd1e)\xb5\xb0\xade*\x81\x99\xfa\xff\xba\xb1\x1fj6\x05\xd6$\x83`\x0c|\xd6\xfbG;\xc9\xfc\x06p\xb1\xa5\xda\xe8m\x8eh\x10L\xf1q!\x10K\xbf\x10\xc6\xc0\xc4\xa5\xf2JAV\x99\xca\xa9a\xb8R \x03\xe6\xe9\xff\x9cQ\x10\xa2\xac\x04\xe3)\xe34`\"\xf1^\xad\x96\xd3\x1f\xad\x9b\xfcm\r[v3\xe8}\xdd=\xd6}\xd2\x98d\xa9\xeb\x1es\x04a!I\x0e\xcdJ&h8\xc4$I\xe7\xb6\x8f\xab\x05\x7fM\xcd\xb2\x81uV\x92UE\r5\x8bb\xc3\xca6o\x19\x0cF\xa3\x1bQ*#\xe9#O(#5\x9f\x0f\xf2z\x0b?\x89L\x01\xc7}3\xc0#\xd0SE\x18\x0f\xd11E\xc2\xe0S\xb4q\xc9\xc5!\x8f\xc70W\x82\xa7\x14\xee\x18\x86rN\xcf\x91s\xc8\xb0\x84pJ&\xa8\xa7D\x0c\xef\xcd\xde\xfcz6[=\xbd4\x92\\\xeaA\xd7/\x96\xc5\x1f\xc0ie\x85}l\x00K\xf4\xfco\\.D\xb6\x90\xfc\xa4\x04\xa5\xd6)\xec\x9ca\x991\x1af\x9f7\xe4\xc6\x05kD\xa3\xd0\xc7\xaa\xba\xae\xe8\xf9\xde\xcb-\xbb\xc4\x9b\x02\x01^4\xc3\xe8^|p\x97f\xfb4\x90\xcb\x9b\x81\x9b\xc2cr\xb6H}tcd2\xa5\xf2\xd8\xf1,\xe7e\xc8.\xd4\xdfY\xad8\x1c\xb5_\xba\xda\xf4\x10\xd2?\xdd\xaeO>\xf5;\xf3+\xf9\xfdj\xf5\xc7\x81\xd7\xe4\xb7\x8a\x91\xcc\xa4S\xfa\x06\xc9\xce]\x91\x81\x89\xa8\x1fU\xeeS\x9f\\\xf5\xe8\xe9\xdf\xc7\xfe\xe4\xa8\xf3\xaaB\xfd(&h\xc8\x04r\x85\x8a\x0b\xbc\xf2M\x88\x05\xe7\x8b\xfc\xb4\xed*e\x93\x9aM\xab\x98i3\xbb\xcf*\xa6A\x9aa\xf9\xcdu\x895A\xd5\xd4\x0b\xdeK\xfd\xea3\xde\x14P\xbf\x1b\xba\xbd\xddh|\xea7\x9d\xd96\xb6\x19\xcf\xb0O\xf11\xf6\x92\x1e\xd6\xc7>F&.\x97\xc7=\x17\xb2JI\xa5N\xb3!\xf7\xe2\xad\xbeK#4\xe4~\xad\x9f\x93O\xb0\xd7\x1d&\xec\xd2l7\xf0a\xfb\x13\xc3\x16\xd6\x17$fN\xfb#\xf5\xbc\x88<m\xe0\x87?\x8eJ_\xed\x9f\xf4\xd0\xc5\xccEJ)\x15\xe34M\x02\xe6\xa3\xd5\x86\xe1\x92\x0b^.xvR\xe9\nj\x80\xd6\x1b\xa6e\x86\xbd\xbb\x15\x1b\xa6[8\xef27U\xaas\xe8\\\xd0W61?{\xd8\xce\xb5~\xdb?\x9a\x87\x1fH\xe6S\xa7/\xef\xe8\xa8\xbd\xed\xcd1\xc7e\x1f\xd5'Nq\x16\x01e\xf1h\xab\xb4\xcc2\xea\x80\x8e6\xa9\xceM\xd97\x17\xae9\xed\xcb\xee\xf1G\xff\x00}\x0f;\xbd\xff\x90|\xc1\x06vo\xbe\xd3j\xf5\xf7=r\x87\xed\xbc\xca\x8e\xafV.\xf45w5\xe5F\xde\xf9T\x06^\xa2\x12#\xc7\xb0Fs\xaf\x16\x19\xa8\a\xfe*\xf4\xd8:\x87\x97N\xb1T5M\r\x83e`\xafu\xad*V\xb55Z}\xad\n\xec\xe0\xc8>1?s*\xf3Yw_\xd21\xc4l\xb7H\xe63_\xf6\x03f\x19v\xdc#\x1d\xde\xbe\x05/\xc4J\xb7\x9b\x8a\xcf\xdd\x06&^*\x8f\xbd\xe4U\x9a\x93\x01u\xec\xa9Q8\xf6\xd9l:[w\xec\x96m\xfa\xd5\x99m\xda\xb0\xe8\xe7\xe1\xa1K\xd6\xb6c\xc7}\xe0b\xd7\x0f\xff\xa2\x05\xac\xf1\xbe\xb0\x0cp\x0f\xa4q<Mu\xfaV\xa9\xe3\xbb\xd0\xd7\xca\xc0\xe6E\xce\xa8\x04\xb0\x1e\xe1\x1073f\xf8W\x98\xef\x19\x193\xb2\xd8\xe2\xa4\xeaq\xbd\x93\xb9(S\x86\xf3&T_opmkqe\xc9\x047\xb0\xdaE\x96\xd6\xd4\x0b\xdf[\x01bV\x01_qR\xc3\x9a\x80\\~\x01\xac\x9a~\xb0\x0f\x15\xf92\x17=\xc3O\xe5\xee\xe3\x7f\tM^R\xf9\xf0+\x85s,\xc2\x1d\xfc\xa0\xcd\xf3b\x06\xff+\xa2\xbdK\x8b\xad\x85\xe0LR\xd1\xdd\x82\xa5\xd4f\xa3V}\x7f\xed&\xb7o\xca\xba\xcd\xbcY\xf3q\x04\x1c\xdb\x8c\x0e~:\x95\xaf\xd9\xb2Bn4/\xda\x86q\x95\xe2.\xa2*\xdc4\x15\xce\x89E\xad8 \x96\xad\xb0+\xe6\xff\xc7v\x8bsB\xfds\\\x86}pwC\xdf\xea\xa3\xe8\xfcw\xcc\xe0\x11\r\x1f\xde\x14\x9cL\t\x03\x80\xb2(\xa8W;\x80D\x7fR/Wo\xcdi*\xc3P\x85h\xc6\x00h\x8d]\x04\xf0\xe3\xc5\xea\x10\xfdr\xd5\xc2\xfa\xbe5;|\x89c\x83r\x16k\xbclA\xcc\xf4q\x9e\xff\x03\x00\x00\xff\xff"

**Comment by hamishforbes** [comment]
Do you have minimal config that reproduces this?
We have used a similar setup in production for a long time now without any problems.

You can bind to the before_request event and force `Accept-Encoding: gzip` there to ensure the origin always compresses.

Note that having ESI on will result in the response being decompressed and saved as plain text.

**Comment by keen99** [comment]
> Do you have minimal config that reproduces this?

working on putting together a stripped down version for repro.

> You can bind to the before_request event and force Accept-Encoding: gzip there to ensure the origin always compresses.

Mm.  What should I set in there?  ```req.header``` isn't right....that just causes ledge to think the client set it.  

if this used proxy_pass to talk to the upstream I'd normally do ```proxy_set_header Accept-Encoding gzip```

**Comment by hamishforbes** [comment]
```lua
local function force_gzip(req_params)
    req_params.headers["Accept-Encoding"] = "gzip"
end
ledge:bind("before_request", force_gzip)
```

Hope that helps!

**Comment by keen99** [comment]
yep, I'd just found the right part of ledge.lua when that came in.

       ledge:bind("before_request", function(req_params)
            req_params.headers["Accept-Encoding"] = "gzip"
       end)

works as well. 

Might be another example for the docu - "to override upstream request headers..."

**Comment by keen99** [comment]
ok, I think I isolated my problem:

doing an ```lpop``` on the body key in redis-cli seems to break the compressed cached content.  No (apparently) issue doing that to uncompressed content, though.

I'm far from an expert on what redis commands do what - but I'm not sure an lpop should corrupt a value...??


My testing case that resulted in this:   request MISS, lpop to confirm the content was compressed, request HIT.  


If I dont lpop the body, everything appears to continue happily.

**Comment by hamishforbes** [comment]
Oh yes, sorry I missed that you were doing lpop!
lpop will actually remove the first entry in the list, so yeah you'll break the body as the first chunk will be missing :)

You want lindex http://redis.io/commands/lindex which will just return it without popping it :)

**Comment by keen99** [comment]
ahh ha!  (why redis can't just have a friendly get (or humanget or read or prettyprint or whatever) that can safely return all types of data...well..)

I wonder if there would be a valid case for a "if the compressed body was non-zero, but the uncompressed body is zero, invalidate the cache" test here?

```2016/06/07 15:56:15 [debug] 24#0: *44 [lua] ledge.lua:2047: e(): #e: gzip_inflate_enabled
2016/06/07 15:56:15 [debug] 24#0: *44 [lua] ledge.lua:2074: e(): #a: install_gzip_decoder
2016/06/07 15:56:15 [debug] 24#0: *44 [lua] ledge.lua:632: filter_body_reader(): gzip_decoder(cache_body_reader)
2016/06/07 15:56:15 [debug] 24#0: *44 [lua] ledge.lua:2037: e(): #t: preparing_response
2016/06/07 15:56:15 [debug] 24#0: *44 [lua] ledge.lua:2047: e(): #e: response_ready
2016/06/07 15:56:15 [debug] 24#0: *44 [lua] ledge.lua:2074: e(): #a: set_http_status_from_response
```

**Comment by keen99** [comment]
ok, for future readers - a roughly minimal example for compressing an upstream that won't compress for you, so you can store compressed content in redis:

```
    ## gzip everything
    server {
      proxy_buffering off;
      gzip on;
      ## you might want to be restrictive here
      gzip_types *;
      # gzip_types      text/plain application/xml application/json;
      gzip_proxied any;
      # gzip_proxied no-cache no-store private expired auth;

      listen 8090;
      location / {
        proxy_pass http://your_upstream_server;
      }
    }

    server {
      proxy_buffering off;
      listen 8080;

      location / {

        lua_check_client_abort on;
        if_modified_since off;

        content_by_lua_block {

          ledge:config_set("upstream_host", "127.0.0.1")
          ledge:config_set("upstream_port", "8090")

          ## override the upstream request header to tell it to compress
          ledge:bind("before_request", function(req_params)
            req_params.headers["Accept-Encoding"] = "gzip"
          end)

          ledge:run()

        } #lua block
      } #location
    } #server
```

**Comment by keen99** [comment]
Just to note for the above setup - there seems to be a bug around serving stale content during errors that returns compressed data..... haven't been able to take the time to track it down, and will update when I do.
