### ISSUE TITLE
redis errors w/ qless background jobs and non-localhost redis with auth

### ISSUE THREAD

**Issue by keen99** [pintsized/ledge#120]
Ok, next issue:

We use redislabs to host our HA redis solution for us - that means non-localhost, and password authentication.

I had to skip the run_workers init to get ledge working because of connection failures - this just tries to connect to localhost redis:

    init_worker_by_lua_block {
       ledge:run_workers()
    }

I was able to kludge this around a bit by hacking on some code to get it to connect to a specified redis, but that didn't work with password auth.

Of course, without this - looks like our redis storage is growing significately - for 1037 unique URIs cached, we have 3674 body keys..     Presumably because the background cleanup jobs aren't cleaning up.

I'll get better repro on this soon (and logs), but wanted to throw this out there in case I'm missing something entirely and there's an easy and documented way to get qless to talk to remote password auth redis... :)

thanks.

**Comment by keen99** [comment]
With:

```
init_worker_by_lua_block {
   ledge:run_workers()
}
```

Results in:

```
2016/06/07 18:12:54 [notice] 10#0: start worker processes
2016/06/07 18:12:54 [notice] 10#0: start worker process 11
2016/06/07 18:12:55 [error] 11#0: connect() failed (111: Connection refused), context: ngx.timer
2016/06/07 18:12:55 [error] 11#0: [lua] connector.lua:224: connect(): connection refused for 127.0.0.1:6379, context: ngx.timer
2016/06/07 18:12:55 [error] 11#0: [lua] worker.lua:48: qless could not connect to Redis: connection refused, context: ngx.timer
2016/06/07 18:12:56 [error] 11#0: connect() failed (111: Connection refused), context: ngx.timer
2016/06/07 18:12:56 [error] 11#0: [lua] connector.lua:224: connect(): connection refused for 127.0.0.1:6379, context: ngx.timer
2016/06/07 18:12:56 [error] 11#0: [lua] worker.lua:48: qless could not connect to Redis: connection refused, context: ngx.timer
2016/06/07 18:12:57 [error] 11#0: connect() failed (111: Connection refused), context: ngx.timer
```


Which makes some amount of sense - we haven't configured ledge to point to a redis at this stage - but it's definitely confusing from the example documentation - especially if you wanted to have different server directives use different redis configs.



So I set my redis config here and give up the idea of using different redis endpoints for different server directives:

```
    init_worker_by_lua_block {

      ledge:config_set("redis_host", { host = "pub-redis-.....ec2.garantiadata.com", port = 321123, password = "example", socket = nil })
      ledge:run_workers()
    }
```

```
2016/06/07 18:16:08 [notice] 9#0: start worker processes
2016/06/07 18:16:08 [notice] 9#0: start worker process 10
2016/06/07 18:16:10 [error] 10#0: connect() failed (111: Connection refused), context: ngx.timer
2016/06/07 18:16:10 [error] 10#0: [lua] connector.lua:224: connect(): connection refused for 127.0.0.1:6379, context: ngx.timer
2016/06/07 18:16:10 [error] 10#0: [lua] ledge.lua:1569: e(): connection refused, context: ngx.timer
2016/06/07 18:16:10 [error] 10#0: [lua] ledge.lua:1581: e(): sleeping for 5s before reconnecting..., context: ngx.timer
```


Same result.

**Comment by keen99** [comment]
We have 3 places that 6379 is referenced, so lets isolate it by changing each one to a different port:

```
lualib/ledge_cache//ledge/ledge.lua:        redis_host = { host = "127.0.0.1", port = 6379, socket = nil, password = nil },
lualib/ledge_cache//resty/qless.lua:    port = 6379,
lualib/ledge_cache//resty/redis/connector.lua:    port = 6379,
```


After changing all 3 of them but not changing the configs it get's interesting - we now get 2 different failures:

```
2016/06/07 18:21:13 [notice] 9#0: start worker processes
2016/06/07 18:21:13 [notice] 9#0: start worker process 10
2016/06/07 18:21:14 [error] 10#0: lua tcp socket connect timed out, context: ngx.timer
2016/06/07 18:21:14 [error] 10#0: [lua] connector.lua:224: connect(): timeout for pub-......us-west-2-1.1.ec2.garantiadata.com:321123, context: ngx.timer
2016/06/07 18:21:14 [error] 10#0: [lua] worker.lua:48: qless could not connect to Redis: timeout, context: ngx.timer
2016/06/07 18:21:15 [error] 10#0: lua tcp socket connect timed out, context: ngx.timer
2016/06/07 18:21:15 [error] 10#0: [lua] connector.lua:224: connect(): timeout for pub-......us-west-2-1.1.ec2.garantiadata.com:321123, context: ngx.timer
2016/06/07 18:21:15 [error] 10#0: [lua] worker.lua:48: qless could not connect to Redis: timeout, context: ngx.timer
2016/06/07 18:21:17 [error] 10#0: connect() failed (111: Connection refused), context: ngx.timer
2016/06/07 18:21:17 [error] 10#0: [lua] connector.lua:224: connect(): connection refused for 127.0.0.1:6380, context: ngx.timer
2016/06/07 18:21:17 [error] 10#0: [lua] ledge.lua:1569: e(): connection refused, context: ngx.timer
2016/06/07 18:21:17 [error] 10#0: [lua] ledge.lua:1581: e(): sleeping for 5s before reconnecting..., context: ngx.timer
2016/06/07 18:21:22 [error] 10#0: connect() failed (111: Connection refused), context: ngx.timer
2016/06/07 18:21:22 [error] 10#0: [lua] connector.lua:224: connect(): connection refused for 127.0.0.1:6380, context: ngx.timer
2016/06/07 18:21:22 [error] 10#0: [lua] ledge.lua:1569: e(): connection refused, context: ngx.timer
2016/06/07 18:21:22 [error] 10#0: [lua] ledge.lua:1581: e(): sleeping for 10s before reconnecting..., context: ngx.timer
```



Lets isolate the 6380 failure:

```
lualib/ledge_cache//ledge/ledge.lua:        redis_host = { host = "127.0.0.1", port = 6380, socket = nil, password = nil },
```

But that doesn't make sense, didn't we set redis_host?

```
      ledge:config_set("redis_host", { host = "pub-redis-.....ec2.garantiadata.com", port = 321123, password = "example", socket = nil })
      ledge:run_workers()
    }
```



.....so now things are just weird.

**Comment by pintsized** [comment]
I'm a bit confused by this, can you explain what you're trying to achieve, and post your configuration? The workers must use the same redis configuration as everything else, so typically you'd set these config options on a global instance of ledge during init, and everything follows from there.

If you need to connect to different redis instances, then use separate ledge instances.

I appreciate the docs are pretty thin, I am hoping to do something about that soon!

**Comment by keen99** [comment]
> I'm a bit confused by this, can you explain what you're trying to achieve, and post your configuration? The workers must use the same redis configuration as everything else, so typically you'd set these config options on a global instance of ledge during init, and everything follows from there.


Let me turn your question around and use the minimal configuration from the docs -  

What is the appropriate modification to this to set redis host, port, and password to be used by all ledge components?   (accepting that we can only have a single ledge talking to a single redis, which was only a future plan)

```
nginx {
    if_modified_since Off;
    lua_check_client_abort On;
    resolver 8.8.8.8;

    lua_package_path '/path/to/lua-resty-http/?.lua;/path/to/lua-resty-redis-connector/?.lua;/path/to/lua-resty-qless/?.lua;/path/to/lua-resty-cookie/?.lua;/path/to/ledge/?.lua;;';

    init_by_lua '
        local ledge_m = require "ledge.ledge"
        ledge = ledge_m.new()
        ledge:config_set("upstream_host", "HOST.EXAMPLE.COM")
    ';

    init_worker_by_lua 'ledge:run_workers()';

    server {
        location / {
            'ledge:run()';
        }
    }
}
```

**Comment by keen99** [comment]
```

user nginx;

daemon off;

#error_log stderr debug;
error_log stderr info;

events {
}

http {


    resolver 127.0.0.1;

    error_log stderr debug;
    #error_log stderr info;
    access_log /dev/stdout;

    include       mime.types;


    lua_package_path ";;${prefix}/lualib/?.lua;${prefix}/lualib/ledge_cache/?.lua";

    init_by_lua '
        local ledge_m = require "ledge.ledge"
        ledge = ledge_m.new()

       ledge:config_set("redis_host", { host = "pub-redis-EXAMPLE.us-west-2-1.1.ec2.garantiadata.com", port = EXAMPLE, password = "EXAMPLE", socket = nil })
    ';

    ## dsr - DO NOT init the workers, we dont need the background workers
    ## and they consume qless, which doesn't work with non-localhost redis
    init_worker_by_lua_block {
      ledge:run_workers()
    }


    server {
      proxy_buffering off;
      listen 8080;

      location / {

        lua_check_client_abort on;
        if_modified_since off;

        content_by_lua_block {

          ledge:config_set("upstream_host", "www.google.com")
          ledge:config_set("upstream_port", "80")

          ledge:bind("origin_fetched", function(res)
                res.header["Cache-Control"] = "max-age=" .. 3000
          end)

          ledge:config_set("cache_key_spec", { ledge:config_get("upstream_host"), ngx.var.uri, ngx.var.args })

          ledge:run()

        } #lua block
      } #location
    } #server
} #http

```



Results in:



```
Successfully built f73b6f0aecbf
2016/06/08 14:45:48 [notice] 9#0: using the "epoll" event method
2016/06/08 14:45:48 [notice] 9#0: openresty/1.9.7.2
2016/06/08 14:45:48 [notice] 9#0: built by gcc 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)
2016/06/08 14:45:48 [notice] 9#0: OS: Linux 4.1.13-boot2docker
2016/06/08 14:45:48 [notice] 9#0: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2016/06/08 14:45:48 [notice] 9#0: start worker processes
2016/06/08 14:45:48 [notice] 9#0: start worker process 10
2016/06/08 14:45:53 [error] 10#0: lua tcp socket connect timed out, context: ngx.timer
2016/06/08 14:45:53 [error] 10#0: [lua] connector.lua:228: connect(): timeout for pub-redis-EXAMPLE.us-west-2-1.1.ec2.garantiadata.com:EXAMPLE, context: ngx.timer
2016/06/08 14:45:53 [error] 10#0: [lua] worker.lua:48: qless could not connect to Redis: timeout, context: ngx.timer
2016/06/08 14:45:54 [error] 10#0: lua tcp socket connect timed out, context: ngx.timer
2016/06/08 14:45:54 [error] 10#0: [lua] connector.lua:228: connect(): timeout for pub-redis-EXAMPLE.us-west-2-1.1.ec2.garantiadata.com:EXAMPLE, context: ngx.timer
2016/06/08 14:45:54 [error] 10#0: [lua] worker.lua:48: qless could not connect to Redis: timeout, context: ngx.timer
2016/06/08 14:45:55 [error] 10#0: lua tcp socket connect timed out, context: ngx.timer
2016/06/08 14:45:55 [error] 10#0: [lua] connector.lua:228: connect(): timeout for pub-redis-EXAMPLE.us-west-2-1.1.ec2.garantiadata.com:EXAMPLE, context: ngx.timer
2016/06/08 14:45:55 [error] 10#0: [lua] worker.lua:48: qless could not connect to Redis: timeout, context: ngx.timer
2016/06/08 14:45:56 [error] 10#0: lua tcp socket connect timed out, context: ngx.timer
2016/06/08 14:45:56 [error] 10#0: [lua] connector.lua:228: connect(): timeout for pub-redis-EXAMPLE.us-west-2-1.1.ec2.garantiadata.com:EXAMPLE, context: ngx.timer
2016/06/08 14:45:56 [error] 10#0: [lua] worker.lua:48: qless could not connect to Redis: timeout, context: ngx.timer
2016/06/08 14:45:57 [error] 10#0: lua tcp socket connect timed out, context: ngx.timer
2016/06/08 14:45:57 [error] 10#0: [lua] connector.lua:228: connect(): timeout for pub-redis-EXAMPLE.us-west-2-1.1.ec2.garantiadata.com:EXAMPLE, context: ngx.timer

```

**Comment by pintsized** [comment]
That looks correct (setting the config globally during init). Have you tried bumping the redis connection timeout in the same place? Seems odd though.

**Comment by keen99** [comment]
ok, with redis config'd in the init - I found the root problem - we're falling back on a 100 timeout (ms?) down this path - 

https://github.com/pintsized/lua-resty-redis-connector/blob/master/lib/resty/redis/connector.lua#L44

    connect_timeout = 100,

Both the ledge default of 500 at
https://github.com/pintsized/ledge/blob/master/lib/ledge/ledge.lua#L223

nor my init_by_lua config:

            ledge:config_set("redis_connect_timeout", 100000)

Are being picked up down the qless path - it's unclear to me exactly how to fix that right now.... but if I set the default connect_timeout in connector.lua to 9000, and set my global to 2000, and drop a print in connect_to_host in connector.lua:
```
function _M.connect_to_host(self, host)
    local r = redis.new()
    r:set_timeout(self.connect_timeout)

print( "DSR: self.connect_timeout ", self.connect_timeout)
...
```

I start seeing 9000's from the worker, and when I hit the proxy, I see 2000 from the cache.

```
2016/06/08 17:16:58 [notice] 16#0: [lua] connector.lua:211: connect(): DSR: self.connect_timeout 9000, context: ngx.timer
```
```
2016/06/08 17:17:02 [debug] 16#0: *7 [lua] ledge.lua:2043: e(): #t: connecting_to_redis
2016/06/08 17:17:02 [notice] 16#0: *7 [lua] connector.lua:211: connect(): DSR: self.connect_timeout 2000, client: 192.168.59.3, server: , request: "GET / HTTP/1.1", host: "192.168.59.103:32969"
```

**Comment by keen99** [comment]
my theory - timeouts are set in connection_options - 
https://github.com/pintsized/ledge/blob/master/lib/ledge/ledge.lua#L376
    local connection_options = {
        connect_timeout = self:config_get("redis_connect_timeout"),
        read_timeout = self:config_get("redis_read_timeout"),
    }

And expected to be passed when creating the worker:
https://github.com/pintsized/ledge/blob/master/lib/ledge/ledge.lua#L381
      local worker = resty_qless_worker.new(redis_params, connection_options)

but worker.new doesn't actually accept them (I'm assuming lua ignores them in this case):

https://github.com/pintsized/lua-resty-qless/blob/master/lib/resty/qless/worker.lua#L33
```
function _M.new(redis_params)
    return setmetatable({
        redis_params = redis_params,
        middleware = nil,
    }, mt)
end
```

Following this further, start also doesn't consume them....

https://github.com/pintsized/lua-resty-qless/blob/master/lib/resty/qless/worker.lua#L46

and I stopped following it down the rabbit hole at this point.

**Comment by pintsized** [comment]
Ah yes, that's a bug then. Thanks - will try and sort it today. Redis failing to connect within 100ms however isn't a great situation. You might want to investigate that.

**Comment by pintsized** [comment]
Fixed over here: https://github.com/pintsized/lua-resty-qless/releases/tag/v0.07

**Comment by keen99** [comment]
> Redis failing to connect within 100ms however isn't a great situation. You might want to investigate that.

docker on osx on the wrong side of the country on cable - 60ms rtt just for icmp, so 100ms for a full three way it's not so surprising for it to fail 100% of the time. :)    might not have trigged that in production - but I dont think "doesn't work on my box, but works in prod" is  meme yet. :)

appreciate your hard work on this!
