### ISSUE TITLE
garbage collection without the garbage collection jobs?

### ISSUE THREAD

**Issue by keen99** [pintsized/ledge#122]
so due to a misconfiguration and a bug - the background worker jobs haven't been running.  (and there were no ql: keys in the database, so no garbage collection queue?)

I've got a large percentage of stale keys in storage now due this that I'd like to safely purge - without impacting the active cache set.

Is there a way to manually (internally or externally) trigger garbage collection at this stage?  A way to filter out the active or inactive keys?

For most caches with short cache lives, the TTL expiration would probably be fine - but we set max-age to 1 year, and the TTLs reflect this. :)

thanks

**Comment by pintsized** [comment]
You'll need to write a script which scans the keyspace looking for orphaned entities. It's a bit tricky to be honest, you might best just to fix things and start again.

Essentially the `*::key` key will point to the active entity (by a hex value). The `*::entities` sorted set will contain all of the entities for the cache item - only one of them is the active one. So you want to remove each of the others from both the sorted set, and actually from the keyspace.

**Comment by keen99** [comment]
ahh ::entities, ok, cool.  should be straight forward enough then.

and if I spent a month writing a tool for it it's still cheaper than having
to refresh this cache.  stupidly expensive API on the other end. :)
