### ISSUE TITLE
Multiple Expires headers in proxied response cause 500

### ISSUE THREAD

**Issue by benagricola** [pintsized/ledge#128]
```
2016/09/15 12:54:56 [error] 23241#0: *795861985 [lua] utils.lua:128: log_action_err(): content phase - action "run_ledge": /opt/repos/ledge/lib/ledge/response.lua:100: bad argument #1 to 'ngx_parse_http_time' (string expected, got table)
```

This happened due to an origin server incorrectly duplicating the `Expires` header (as `expires`) due to misconfiguration, which turns `self.header["Expires"]` into a table since these are normalised.

Fix may be to only look at the first or the last header in the table if it exists, or assume `Expires: 0` when multiple headers are seen, or assume the highest value.

Thoughts?

**Comment by pintsized** [comment]
Went with picking the last one since ngx_lua does that elsewhere when setting headers.
