### ISSUE TITLE
Support for Redis 3.x.x

### ISSUE THREAD

**Issue by kimbrandt** [pintsized/ledge#141]
Hello,

I'm just wondering what the plan is for supporting Redis 3.x.x and the clustering features the newer versions offer?

**Comment by pintsized** [comment]
There are a few factors in play here. One is updating lua-resty-qless to pull in the new qless-core which fixes issues with Redis 3.2.x. So you can try the develop branch and that should just work: https://github.com/pintsized/lua-resty-qless/tree/develop

Redis Cluster is a slightly different beast, as there isn't yet an OpenResty library which supports it, although I think there are some attempts knocking around if you search. Cluster also imposes some limitations, which may effect how well it can be used with Ledge.

Finally, Ledge is undergoing quite a significant refactor (see the develop branch, and ignore the docs!), and one of the reasons for this was to abstract the body storage part into a driver system (i.e. to store in other backends). I think this will make Redis Cluster a possibility for the response body storage itself, but we may still need an independent regular Redis in the mix for metadata / jobs etc. This is a bit unclear without further investigation.

**Comment by pintsized** [comment]
Redis >= 3.x.x is now supported in the master branch. Redis Cluster is still missing in the OpenResty ecosystem however.
