### ISSUE TITLE
Logging Cache State

### ISSUE THREAD

**Issue by hamishforbes** [pintsized/ledge#16]
Currently we can use the X-Cache and X-Cache-State response headers in the nginx access log to get a decent idea of what happened with each request.

However for requests that are uncacheable (Have cache-control: no-cache or whatever) those headers aren't sent and thus we just get an empty bit in the logfile.

It would also be nice to be able to log a bit more detailed information without filling the response with headers, things like was this a collapsed request or was it a 'negative hit' etc.

So maybe if we can push a state variable back to nginx and just add that to the log format?

**Comment by keen99** [comment]
As a heads up to the next person who reads this thread looking for logging:

The examples above wont work anymore (5/23/16) - the code to support the variables was removed.  I ran out of time trying to backtrack when it was removed. 

An example using combined + the available headers:

```
    log_format ledge '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent" '
                    '"Cache:$sent_http_x_cache"  "Age:$sent_http_age" "Via:$sent_http_via"'
                    ;

    access_log /var/log/nginx/access_log ledge;
```

```
192.168.59.3 - - [23/May/2016:22:22:18 +0000] "GET /x/y/z HTTP/1.1" 200 57840 "-" "curl/7.37.1""Cache:HIT from 159e8241f519:8080"  "Age:724"
```
