### ISSUE TITLE
luarocks install Error: No results matching query were found.

### ISSUE THREAD

**Issue by wmzy** [pintsized/ledge#170]
```bash
➜  work luarocks --local install lua-resty-http
Installing https://luarocks.org/lua-resty-http-0.12-0.src.rock...
Using https://luarocks.org/lua-resty-http-0.12-0.src.rock... switching to 'build' mode
Updating manifest for /home/xxx/.luarocks/lib64/luarocks/rocks
lua-resty-http 0.12-0 is now built and installed in /home/xxx/.luarocks (license: 2-clause BSD)

➜  work luarocks --local install ledge         

Error: No results matching query were found.
➜  work lua -v                                                                         
Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio
➜  work luarocks --version                                                             
/usr/local/bin/luarocks 2.3.0
LuaRocks main command-line interface

```

**Comment by wmzy** [comment]
The lua version is too high?
https://github.com/pintsized/ledge/blob/2474cab721dc300b1dbc6ba40121283ba44bea47/ledge-1.28-6.rockspec#L14

**Comment by wmzy** [comment]
Change lua to 5.1.5 solved the problem.
Will you plan to support lua 5.3?

**Comment by hamishforbes** [comment]
No, Openresty uses LuaJIT not PUC Lua.
Luarocks, afaik, doesn't really understand Openresty. 

We should probably switch over to using OPM instead

**Comment by wmzy** [comment]
@hamishforbes Thanks for reply.
The OPM is more similar with npm which I am familiar with.
Great to see the switch.
And I see all the dependents have been published to the OPM registry.
Is there much work to do?
