### ISSUE TITLE
binding globally error:no such event

### ISSUE THREAD

**Issue by wmzy** [pintsized/ledge#171]
It may be a document error.We should use `require("ledge").bind` replace the `require("ledge"):bind` [here](https://github.com/pintsized/ledge/blob/master/README.md#binding-globally).

**Comment by hamishforbes** [comment]
Good spot, the example incorrectly used `:` although the API docs for `handler:bind` and `ledge.bind` do point out the difference: https://github.com/pintsized/ledge#ledgebind
