### ISSUE TITLE
500 if multiple Date headers are sent

### ISSUE THREAD

**Issue by jloh** [pintsized/ledge#180]
At the moment if an upstream host sends more than one `Date` header (which isn't good to begin with) ledge throws a 500 due to the code below

https://github.com/pintsized/ledge/blob/1f5981022479e912af18c81ffffd9bd317cbac81/lib/ledge/handler.lua#L497-L510

Ideally it should handle this a bit more gracefully.

**Comment by hamishforbes** [comment]
As best I can tell it's not valid to send multiple Date response headers, but we should definitely handle this more gracefully than an error and a 500 response.
