### ISSUE TITLE
Generic database interface

### ISSUE THREAD

**Issue by thefosk** [pintsized/ledge#93]
To expand the system beyond Redis and use other datastore, it would be nice to have some sort of interface that defines methods like:
- `delete(key)`
- `get(key)`
- `save(key, value, expiration)`
- etc

To make it easier to implement other datastore besides Redis.

**Comment by pintsized** [comment]
Storage drivers have now been abstracted. Redis is still required for logic / metadata / atomic scripts etc, but cache bodies can be stored wherever you like if a driver is implemented.

Currently the only driver is the Redis one.
